FROM --platform=linux/amd64 tensorflow/tensorflow:2.3.0

COPY ...
RUN python -m pip install --upgrade pip
RUN ...
COPY ...

WORKDIR /app

ENV ...

EXPOSE ...

CMD ["uvicorn", "...", "--host", "0.0.0.0", "--port", "..."]